version: '3.9'
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: realteeth
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      args:
        MODULE_NAME: adapter-in-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/realteeth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: on-failure
    ports:
      - "9090:9090"

  worker:
    build:
      context: .
      args:
        MODULE_NAME: adapter-in-worker
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/realteeth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: on-failure
    ports:
      - "9091:9091"

  batch:
    build:
      context: .
      args:
        MODULE_NAME: adapter-batch
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/realteeth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: on-failure
    ports:
      - "9092:9092"
