version: '3.9'
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: realteeth
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"

#  api:
#    build:
#      context: .
#      dockerfile: adapter-in-api/Dockerfile
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/realteeth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#      SPRING_DATASOURCE_USERNAME: app
#      SPRING_DATASOURCE_PASSWORD: app
#      SPRING_RABBITMQ_HOST: rabbitmq
#    depends_on:
#      - mysql
#      - rabbitmq
#    ports:
#      - "8080:8080"
#
#  worker:
#    build:
#      context: .
#      dockerfile: adapter-in-worker/Dockerfile
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/realteeth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#      SPRING_DATASOURCE_USERNAME: app
#      SPRING_DATASOURCE_PASSWORD: app
#      SPRING_RABBITMQ_HOST: rabbitmq
#      MOCK_WORKER_BASE_URL: https://dev.realteeth.ai
#      MOCK_WORKER_CANDIDATE_NAME: candidate
#      MOCK_WORKER_EMAIL: candidate@example.com
#    depends_on:
#      - mysql
#      - rabbitmq
