rootProject.name = 'realteeth_test'

include 'domain'
include 'application'
include 'adapter-in-api'
include 'adapter-in-worker'
include 'adapter-out-persistence'
include 'adapter-out-mq'
include 'adapter-out-worker'
include 'adapter-out-util'

for (project in rootProject.children) {
    project.projectDir = file("modules/${project.name}")
}