plugins {
    id 'java-library'
}

dependencies {
    // module
    implementation project(':domain')
    implementation project(':application')

    // orm
    api 'org.springframework.boot:spring-boot-starter-data-jpa'

    // db
    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'com.h2database:h2'
}