server:
  port: 9091

spring:
  application:
    name: RealteethWorkerApplication
  profiles:
    include: core

worker:
  baseUrl: https://dev.realteeth.ai
  candidateName: test
  email: test@naver.com